import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import ModalProvider from '@/components/provider/modal-provider'
import { Toaster } from 'sonner'
import ReactQueryProvider from '@/components/provider/react-query-provider'
import { SocketProvider } from '@/components/provider/socket-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Discord clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider attribute='class' defaultTheme='dark' enableSystem={false}>
            <SocketProvider>
              <ReactQueryProvider>
                <ModalProvider />
                {children}
                <Toaster richColors={true} />
              </ReactQueryProvider>
            </SocketProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
